@endpoint_url = http://localhost:8000
@user_id = 684d5b36cd2cc6f9df1ae31d
@user_email = user@example.com
@vault_entry_id = 684e9c67d0c361e9771be068
@vault_entry_key = test
@test_author = user@example.com


# --------------------
# ACCOUNT REQUESTS
# --------------------

### Create a new User account
POST {{endpoint_url}}/setup
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "ThisShouldBeKeptSecret"
}

### Login into a User account
POST {{endpoint_url}}/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "ThisShouldBeKeptSecret"
}

### Logout
POST {{endpoint_url}}/logout


### Get User
GET {{endpoint_url}}/users/{{user_email}}


### Update a User account
PUT {{endpoint_url}}/update/684e7703def17eb1fb8b4c46
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "ThisShouldBeKeptSecret"
}


### Delete User account
DELETE {{endpoint_url}}/delete/user/684d5b36cd2cc6f9df1ae31d



# --------------------
### VAULT REQUESTS
# --------------------

### Create a Vault Entry
POST {{endpoint_url}}/create/vault/entry
Content-Type: application/json

{
    "key": "test",
    "value": "ThisShouldBeKeptSecret",
    "created_by": "user@example.com"
}

### Retrieve All Vault Entries
GET {{endpoint_url}}/retrieve/vault/entries

### Retrieve Vault Entry by ID
GET {{endpoint_url}}/retrieve/vault/entries/{{vault_entry_id}}

### Retrieve Vault Entry by Key
GET {{endpoint_url}}/retrieve/vault/entry/key/{{vault_entry_key}}

### Retrieve Vault Entry by Author
GET {{endpoint_url}}/retrieve/vault/entry/{{test_author}}

### Delete a Vault Entry
DELETE {{endpoint_url}}/delete/{{vault_entry_id}}

