[package]
name = "ec_secrets_manager_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.38"
tokio = "1.45.0"
mongodb = "3.2.3"
serde = "1.0.219"
ec_secrets_shared_library = {path = "../ec_secrets_shared_library"}
bcrypt = "0.17.0"
